apiVersion: v1
kind: Secret
metadata:
  name: aegis-secret
  namespace: aegis
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@aegis-postgres:5432/aegis_db"
  JWT_SECRET: "supersecretproductiontoken"
