"""add_transit_models

Revision ID: 46749e37d8f7
Revises: fa1205a7719f
Create Date: 2026-07-11 22:03:45.351964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46749e37d8f7'
down_revision: Union[str, None] = 'fa1205a7719f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=True)
    op.create_table('parking_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('occupied_spaces', sa.Integer(), nullable=False),
    sa.Column('location_zone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_zones_id'), 'parking_zones', ['id'], unique=False)
    op.create_index(op.f('ix_parking_zones_name'), 'parking_zones', ['name'], unique=True)
    op.create_table('transit_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_audits_id'), 'transit_audits', ['id'], unique=False)
    op.create_table('transit_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_zone', sa.String(length=100), nullable=False),
    sa.Column('capacity_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_hubs_id'), 'transit_hubs', ['id'], unique=False)
    op.create_index(op.f('ix_transit_hubs_name'), 'transit_hubs', ['name'], unique=True)
    op.create_table('transit_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_routes_id'), 'transit_routes', ['id'], unique=False)
    op.create_index(op.f('ix_transit_routes_name'), 'transit_routes', ['name'], unique=False)
    op.create_index(op.f('ix_transit_routes_route_code'), 'transit_routes', ['route_code'], unique=True)
    op.create_table('transit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_stops_id'), 'transit_stops', ['id'], unique=False)
    op.create_index(op.f('ix_transit_stops_name'), 'transit_stops', ['name'], unique=False)
    op.create_index(op.f('ix_transit_stops_stop_code'), 'transit_stops', ['stop_code'], unique=True)
    op.create_table('transit_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_vehicles_id'), 'transit_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_transit_vehicles_vehicle_code'), 'transit_vehicles', ['vehicle_code'], unique=True)
    op.create_table('driver_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_id'), 'driver_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_vehicle_id'), 'driver_assignments', ['vehicle_id'], unique=False)
    op.create_table('shuttle_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transit_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_services_id'), 'shuttle_services', ['id'], unique=False)
    op.create_index(op.f('ix_shuttle_services_name'), 'shuttle_services', ['name'], unique=True)
    op.create_index(op.f('ix_shuttle_services_route_id'), 'shuttle_services', ['route_id'], unique=False)
    op.create_table('transit_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('max_standing', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_capacities_id'), 'transit_capacities', ['id'], unique=False)
    op.create_index(op.f('ix_transit_capacities_vehicle_id'), 'transit_capacities', ['vehicle_id'], unique=True)
    op.create_table('transit_occupancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['transit_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_occupancies_id'), 'transit_occupancies', ['id'], unique=False)
    op.create_index(op.f('ix_transit_occupancies_stop_id'), 'transit_occupancies', ['stop_id'], unique=False)
    op.create_index(op.f('ix_transit_occupancies_vehicle_id'), 'transit_occupancies', ['vehicle_id'], unique=False)
    op.create_table('transit_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('queue_size', sa.Integer(), nullable=False),
    sa.Column('average_wait_time_minutes', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['transit_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_queues_id'), 'transit_queues', ['id'], unique=False)
    op.create_index(op.f('ix_transit_queues_stop_id'), 'transit_queues', ['stop_id'], unique=False)
    op.create_table('transit_route_stops',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transit_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['transit_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id', 'stop_id')
    )
    op.create_table('transit_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.String(length=5), nullable=False),
    sa.Column('arrival_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transit_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_schedules_id'), 'transit_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_transit_schedules_route_id'), 'transit_schedules', ['route_id'], unique=False)
    op.create_table('transit_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_telemetry_id'), 'transit_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_transit_telemetry_vehicle_id'), 'transit_telemetry', ['vehicle_id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transit_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_id'), 'vehicle_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_route_id'), 'vehicle_assignments', ['route_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_table('transit_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['transit_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['transit_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_trips_driver_id'), 'transit_trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_transit_trips_id'), 'transit_trips', ['id'], unique=False)
    op.create_index(op.f('ix_transit_trips_schedule_id'), 'transit_trips', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_transit_trips_vehicle_id'), 'transit_trips', ['vehicle_id'], unique=False)
    op.create_table('transit_delays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['transit_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_delays_id'), 'transit_delays', ['id'], unique=False)
    op.create_index(op.f('ix_transit_delays_trip_id'), 'transit_delays', ['trip_id'], unique=False)
    op.create_table('transit_etas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['transit_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['transit_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_etas_id'), 'transit_etas', ['id'], unique=False)
    op.create_index(op.f('ix_transit_etas_stop_id'), 'transit_etas', ['stop_id'], unique=False)
    op.create_index(op.f('ix_transit_etas_trip_id'), 'transit_etas', ['trip_id'], unique=False)
    op.create_table('transit_incident_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['transit_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['transit_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_incident_links_id'), 'transit_incident_links', ['id'], unique=False)
    op.create_index(op.f('ix_transit_incident_links_incident_id'), 'transit_incident_links', ['incident_id'], unique=False)
    op.create_index(op.f('ix_transit_incident_links_route_id'), 'transit_incident_links', ['route_id'], unique=False)
    op.create_index(op.f('ix_transit_incident_links_trip_id'), 'transit_incident_links', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transit_incident_links_trip_id'), table_name='transit_incident_links')
    op.drop_index(op.f('ix_transit_incident_links_route_id'), table_name='transit_incident_links')
    op.drop_index(op.f('ix_transit_incident_links_incident_id'), table_name='transit_incident_links')
    op.drop_index(op.f('ix_transit_incident_links_id'), table_name='transit_incident_links')
    op.drop_table('transit_incident_links')
    op.drop_index(op.f('ix_transit_etas_trip_id'), table_name='transit_etas')
    op.drop_index(op.f('ix_transit_etas_stop_id'), table_name='transit_etas')
    op.drop_index(op.f('ix_transit_etas_id'), table_name='transit_etas')
    op.drop_table('transit_etas')
    op.drop_index(op.f('ix_transit_delays_trip_id'), table_name='transit_delays')
    op.drop_index(op.f('ix_transit_delays_id'), table_name='transit_delays')
    op.drop_table('transit_delays')
    op.drop_index(op.f('ix_transit_trips_vehicle_id'), table_name='transit_trips')
    op.drop_index(op.f('ix_transit_trips_schedule_id'), table_name='transit_trips')
    op.drop_index(op.f('ix_transit_trips_id'), table_name='transit_trips')
    op.drop_index(op.f('ix_transit_trips_driver_id'), table_name='transit_trips')
    op.drop_table('transit_trips')
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_route_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_transit_telemetry_vehicle_id'), table_name='transit_telemetry')
    op.drop_index(op.f('ix_transit_telemetry_id'), table_name='transit_telemetry')
    op.drop_table('transit_telemetry')
    op.drop_index(op.f('ix_transit_schedules_route_id'), table_name='transit_schedules')
    op.drop_index(op.f('ix_transit_schedules_id'), table_name='transit_schedules')
    op.drop_table('transit_schedules')
    op.drop_table('transit_route_stops')
    op.drop_index(op.f('ix_transit_queues_stop_id'), table_name='transit_queues')
    op.drop_index(op.f('ix_transit_queues_id'), table_name='transit_queues')
    op.drop_table('transit_queues')
    op.drop_index(op.f('ix_transit_occupancies_vehicle_id'), table_name='transit_occupancies')
    op.drop_index(op.f('ix_transit_occupancies_stop_id'), table_name='transit_occupancies')
    op.drop_index(op.f('ix_transit_occupancies_id'), table_name='transit_occupancies')
    op.drop_table('transit_occupancies')
    op.drop_index(op.f('ix_transit_capacities_vehicle_id'), table_name='transit_capacities')
    op.drop_index(op.f('ix_transit_capacities_id'), table_name='transit_capacities')
    op.drop_table('transit_capacities')
    op.drop_index(op.f('ix_shuttle_services_route_id'), table_name='shuttle_services')
    op.drop_index(op.f('ix_shuttle_services_name'), table_name='shuttle_services')
    op.drop_index(op.f('ix_shuttle_services_id'), table_name='shuttle_services')
    op.drop_table('shuttle_services')
    op.drop_index(op.f('ix_driver_assignments_vehicle_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_transit_vehicles_vehicle_code'), table_name='transit_vehicles')
    op.drop_index(op.f('ix_transit_vehicles_id'), table_name='transit_vehicles')
    op.drop_table('transit_vehicles')
    op.drop_index(op.f('ix_transit_stops_stop_code'), table_name='transit_stops')
    op.drop_index(op.f('ix_transit_stops_name'), table_name='transit_stops')
    op.drop_index(op.f('ix_transit_stops_id'), table_name='transit_stops')
    op.drop_table('transit_stops')
    op.drop_index(op.f('ix_transit_routes_route_code'), table_name='transit_routes')
    op.drop_index(op.f('ix_transit_routes_name'), table_name='transit_routes')
    op.drop_index(op.f('ix_transit_routes_id'), table_name='transit_routes')
    op.drop_table('transit_routes')
    op.drop_index(op.f('ix_transit_hubs_name'), table_name='transit_hubs')
    op.drop_index(op.f('ix_transit_hubs_id'), table_name='transit_hubs')
    op.drop_table('transit_hubs')
    op.drop_index(op.f('ix_transit_audits_id'), table_name='transit_audits')
    op.drop_table('transit_audits')
    op.drop_index(op.f('ix_parking_zones_name'), table_name='parking_zones')
    op.drop_index(op.f('ix_parking_zones_id'), table_name='parking_zones')
    op.drop_table('parking_zones')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
