"""Add_crowd_models

Revision ID: 21cd8a84aeb3
Revises: 2b3c4d5e6f7a
Create Date: 2026-07-11 11:37:07.289480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cd8a84aeb3'
down_revision: Union[str, None] = '2b3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_zones_id'), 'crowd_zones', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_zones_name'), 'crowd_zones', ['name'], unique=True)
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_categories_id'), 'knowledge_categories', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_categories_name'), 'knowledge_categories', ['name'], unique=True)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_tags_id'), 'knowledge_tags', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_tags_name'), 'knowledge_tags', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_device_id'), 'cameras', ['device_id'], unique=True)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('crowd_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_alerts_id'), 'crowd_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_alerts_triggered_at'), 'crowd_alerts', ['triggered_at'], unique=False)
    op.create_table('crowd_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('threshold_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_thresholds_id'), 'crowd_thresholds', ['id'], unique=False)
    op.create_table('density_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('average_density', sa.Float(), nullable=False),
    sa.Column('peak_density', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_density_metrics_id'), 'density_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_density_metrics_timestamp'), 'density_metrics', ['timestamp'], unique=False)
    op.create_table('egress_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('exit_gate_id', sa.String(), nullable=False),
    sa.Column('flow_velocity', sa.Float(), nullable=False),
    sa.Column('dispersal_rate_per_min', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egress_flows_id'), 'egress_flows', ['id'], unique=False)
    op.create_index(op.f('ix_egress_flows_timestamp'), 'egress_flows', ['timestamp'], unique=False)
    op.create_table('heatmap_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('density_val', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heatmap_tiles_id'), 'heatmap_tiles', ['id'], unique=False)
    op.create_index(op.f('ix_heatmap_tiles_timestamp'), 'heatmap_tiles', ['timestamp'], unique=False)
    op.create_table('ingress_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('turnstile_id', sa.String(), nullable=False),
    sa.Column('scan_rate_per_min', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingress_flows_id'), 'ingress_flows', ['id'], unique=False)
    op.create_index(op.f('ix_ingress_flows_timestamp'), 'ingress_flows', ['timestamp'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_title'), 'knowledge_documents', ['title'], unique=True)
    op.create_table('occupancy_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_count', sa.Integer(), nullable=False),
    sa.Column('capacity_utilization_ratio', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_history_id'), 'occupancy_history', ['id'], unique=False)
    op.create_index(op.f('ix_occupancy_history_timestamp'), 'occupancy_history', ['timestamp'], unique=False)
    op.create_table('zone_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('safe_capacity_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_capacities_id'), 'zone_capacities', ['id'], unique=False)
    op.create_table('camera_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('connectivity_status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_health_id'), 'camera_health', ['id'], unique=False)
    op.create_index(op.f('ix_camera_health_recorded_at'), 'camera_health', ['recorded_at'], unique=False)
    op.create_table('crowd_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('estimated_count', sa.Integer(), nullable=False),
    sa.Column('density_level', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['crowd_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_snapshots_id'), 'crowd_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_snapshots_recorded_at'), 'crowd_snapshots', ['recorded_at'], unique=False)
    op.create_table('document_categories',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'category_id')
    )
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['knowledge_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('knowledge_attachments',
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('virus_scan_status', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_knowledge_attachments_attachment_id'), 'knowledge_attachments', ['attachment_id'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_versions_id'), 'knowledge_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_versions_id'), table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index(op.f('ix_knowledge_attachments_attachment_id'), table_name='knowledge_attachments')
    op.drop_table('knowledge_attachments')
    op.drop_table('document_tags')
    op.drop_table('document_categories')
    op.drop_index(op.f('ix_crowd_snapshots_recorded_at'), table_name='crowd_snapshots')
    op.drop_index(op.f('ix_crowd_snapshots_id'), table_name='crowd_snapshots')
    op.drop_table('crowd_snapshots')
    op.drop_index(op.f('ix_camera_health_recorded_at'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_id'), table_name='camera_health')
    op.drop_table('camera_health')
    op.drop_index(op.f('ix_zone_capacities_id'), table_name='zone_capacities')
    op.drop_table('zone_capacities')
    op.drop_index(op.f('ix_occupancy_history_timestamp'), table_name='occupancy_history')
    op.drop_index(op.f('ix_occupancy_history_id'), table_name='occupancy_history')
    op.drop_table('occupancy_history')
    op.drop_index(op.f('ix_knowledge_documents_title'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_ingress_flows_timestamp'), table_name='ingress_flows')
    op.drop_index(op.f('ix_ingress_flows_id'), table_name='ingress_flows')
    op.drop_table('ingress_flows')
    op.drop_index(op.f('ix_heatmap_tiles_timestamp'), table_name='heatmap_tiles')
    op.drop_index(op.f('ix_heatmap_tiles_id'), table_name='heatmap_tiles')
    op.drop_table('heatmap_tiles')
    op.drop_index(op.f('ix_egress_flows_timestamp'), table_name='egress_flows')
    op.drop_index(op.f('ix_egress_flows_id'), table_name='egress_flows')
    op.drop_table('egress_flows')
    op.drop_index(op.f('ix_density_metrics_timestamp'), table_name='density_metrics')
    op.drop_index(op.f('ix_density_metrics_id'), table_name='density_metrics')
    op.drop_table('density_metrics')
    op.drop_index(op.f('ix_crowd_thresholds_id'), table_name='crowd_thresholds')
    op.drop_table('crowd_thresholds')
    op.drop_index(op.f('ix_crowd_alerts_triggered_at'), table_name='crowd_alerts')
    op.drop_index(op.f('ix_crowd_alerts_id'), table_name='crowd_alerts')
    op.drop_table('crowd_alerts')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_device_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_knowledge_tags_name'), table_name='knowledge_tags')
    op.drop_index(op.f('ix_knowledge_tags_id'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index(op.f('ix_knowledge_categories_name'), table_name='knowledge_categories')
    op.drop_index(op.f('ix_knowledge_categories_id'), table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    op.drop_index(op.f('ix_crowd_zones_name'), table_name='crowd_zones')
    op.drop_index(op.f('ix_crowd_zones_id'), table_name='crowd_zones')
    op.drop_table('crowd_zones')
    # ### end Alembic commands ###
