"""add_volunteer_indexes

Revision ID: fa1205a7719f
Revises: b9521c42f82b
Create Date: 2026-07-11 21:41:10.210934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1205a7719f'
down_revision: Union[str, None] = 'b9521c42f82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_volunteer_assignments_shift_id'), 'volunteer_assignments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_volunteer_assignments_volunteer_id'), 'volunteer_assignments', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_availabilities_volunteer_id'), 'volunteer_availabilities', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_certifications_volunteer_id'), 'volunteer_certifications', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_check_ins_assignment_id'), 'volunteer_check_ins', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_volunteer_check_outs_assignment_id'), 'volunteer_check_outs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_volunteer_emergency_contacts_volunteer_id'), 'volunteer_emergency_contacts', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_locations_volunteer_id'), 'volunteer_locations', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_statuses_volunteer_id'), 'volunteer_statuses', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_statuses_volunteer_id'), table_name='volunteer_statuses')
    op.drop_index(op.f('ix_volunteer_locations_volunteer_id'), table_name='volunteer_locations')
    op.drop_index(op.f('ix_volunteer_emergency_contacts_volunteer_id'), table_name='volunteer_emergency_contacts')
    op.drop_index(op.f('ix_volunteer_check_outs_assignment_id'), table_name='volunteer_check_outs')
    op.drop_index(op.f('ix_volunteer_check_ins_assignment_id'), table_name='volunteer_check_ins')
    op.drop_index(op.f('ix_volunteer_certifications_volunteer_id'), table_name='volunteer_certifications')
    op.drop_index(op.f('ix_volunteer_availabilities_volunteer_id'), table_name='volunteer_availabilities')
    op.drop_index(op.f('ix_volunteer_assignments_volunteer_id'), table_name='volunteer_assignments')
    op.drop_index(op.f('ix_volunteer_assignments_shift_id'), table_name='volunteer_assignments')
    # ### end Alembic commands ###
