"""add_accessibility_models

Revision ID: 6f0b1d413ef2
Revises: 578a6f3b2d1c
Create Date: 2026-07-12 15:45:03.441890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0b1d413ef2'
down_revision: Union[str, None] = '578a6f3b2d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_audits_created_by'), 'accessibility_audits', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_audits_id'), 'accessibility_audits', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_audits_updated_by'), 'accessibility_audits', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_audits_venue_id'), 'accessibility_audits', ['venue_id'], unique=False)
    op.create_table('accessibility_facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_facilities_created_by'), 'accessibility_facilities', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_facility_type'), 'accessibility_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_id'), 'accessibility_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_name'), 'accessibility_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_status'), 'accessibility_facilities', ['status'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_updated_by'), 'accessibility_facilities', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_facilities_venue_id'), 'accessibility_facilities', ['venue_id'], unique=False)
    op.create_table('accessibility_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('map_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_maps_created_by'), 'accessibility_maps', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_maps_id'), 'accessibility_maps', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_maps_status'), 'accessibility_maps', ['status'], unique=False)
    op.create_index(op.f('ix_accessibility_maps_updated_by'), 'accessibility_maps', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_maps_venue_id'), 'accessibility_maps', ['venue_id'], unique=True)
    op.create_table('accessibility_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('start_zone_id', sa.String(length=100), nullable=False),
    sa.Column('end_zone_id', sa.String(length=100), nullable=False),
    sa.Column('impairment_profile', sa.String(length=100), nullable=False),
    sa.Column('route_length_meters', sa.Float(), nullable=False),
    sa.Column('estimated_travel_time_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_routes_created_by'), 'accessibility_routes', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_routes_id'), 'accessibility_routes', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_routes_status'), 'accessibility_routes', ['status'], unique=False)
    op.create_index(op.f('ix_accessibility_routes_updated_by'), 'accessibility_routes', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_routes_venue_id'), 'accessibility_routes', ['venue_id'], unique=False)
    op.create_table('accessibility_barriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('barrier_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('associated_facility_id', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('bms_fault_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associated_facility_id'], ['accessibility_facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_barriers_associated_facility_id'), 'accessibility_barriers', ['associated_facility_id'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_barrier_type'), 'accessibility_barriers', ['barrier_type'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_created_by'), 'accessibility_barriers', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_id'), 'accessibility_barriers', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_severity'), 'accessibility_barriers', ['severity'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_status'), 'accessibility_barriers', ['status'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_updated_by'), 'accessibility_barriers', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_venue_id'), 'accessibility_barriers', ['venue_id'], unique=False)
    op.create_index(op.f('ix_accessibility_barriers_zone_id'), 'accessibility_barriers', ['zone_id'], unique=False)
    op.create_table('accessibility_waypoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('audio_uri', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['accessibility_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_waypoints_created_by'), 'accessibility_waypoints', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_waypoints_id'), 'accessibility_waypoints', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_waypoints_route_id'), 'accessibility_waypoints', ['route_id'], unique=False)
    op.create_index(op.f('ix_accessibility_waypoints_updated_by'), 'accessibility_waypoints', ['updated_by'], unique=False)
    op.create_table('accessible_entrances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('queue_length_seconds', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['accessibility_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessible_entrances_created_by'), 'accessible_entrances', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessible_entrances_facility_id'), 'accessible_entrances', ['facility_id'], unique=True)
    op.create_index(op.f('ix_accessible_entrances_id'), 'accessible_entrances', ['id'], unique=False)
    op.create_index(op.f('ix_accessible_entrances_updated_by'), 'accessible_entrances', ['updated_by'], unique=False)
    op.create_table('elevator_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('bms_fault_code', sa.String(length=100), nullable=True),
    sa.Column('last_telemetry_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['accessibility_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elevator_statuses_created_by'), 'elevator_statuses', ['created_by'], unique=False)
    op.create_index(op.f('ix_elevator_statuses_facility_id'), 'elevator_statuses', ['facility_id'], unique=True)
    op.create_index(op.f('ix_elevator_statuses_id'), 'elevator_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_elevator_statuses_is_operational'), 'elevator_statuses', ['is_operational'], unique=False)
    op.create_index(op.f('ix_elevator_statuses_updated_by'), 'elevator_statuses', ['updated_by'], unique=False)
    op.create_table('ramp_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('is_obstructed', sa.Boolean(), nullable=False),
    sa.Column('obstruction_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['accessibility_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ramp_statuses_created_by'), 'ramp_statuses', ['created_by'], unique=False)
    op.create_index(op.f('ix_ramp_statuses_facility_id'), 'ramp_statuses', ['facility_id'], unique=True)
    op.create_index(op.f('ix_ramp_statuses_id'), 'ramp_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_ramp_statuses_is_obstructed'), 'ramp_statuses', ['is_obstructed'], unique=False)
    op.create_index(op.f('ix_ramp_statuses_updated_by'), 'ramp_statuses', ['updated_by'], unique=False)
    op.create_table('accessibility_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('barrier_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barrier_id'], ['accessibility_barriers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_alerts_barrier_id'), 'accessibility_alerts', ['barrier_id'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_created_by'), 'accessibility_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_id'), 'accessibility_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_severity'), 'accessibility_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_status'), 'accessibility_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_updated_by'), 'accessibility_alerts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accessibility_alerts_venue_id'), 'accessibility_alerts', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessibility_alerts_venue_id'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_updated_by'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_status'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_severity'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_id'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_created_by'), table_name='accessibility_alerts')
    op.drop_index(op.f('ix_accessibility_alerts_barrier_id'), table_name='accessibility_alerts')
    op.drop_table('accessibility_alerts')
    op.drop_index(op.f('ix_ramp_statuses_updated_by'), table_name='ramp_statuses')
    op.drop_index(op.f('ix_ramp_statuses_is_obstructed'), table_name='ramp_statuses')
    op.drop_index(op.f('ix_ramp_statuses_id'), table_name='ramp_statuses')
    op.drop_index(op.f('ix_ramp_statuses_facility_id'), table_name='ramp_statuses')
    op.drop_index(op.f('ix_ramp_statuses_created_by'), table_name='ramp_statuses')
    op.drop_table('ramp_statuses')
    op.drop_index(op.f('ix_elevator_statuses_updated_by'), table_name='elevator_statuses')
    op.drop_index(op.f('ix_elevator_statuses_is_operational'), table_name='elevator_statuses')
    op.drop_index(op.f('ix_elevator_statuses_id'), table_name='elevator_statuses')
    op.drop_index(op.f('ix_elevator_statuses_facility_id'), table_name='elevator_statuses')
    op.drop_index(op.f('ix_elevator_statuses_created_by'), table_name='elevator_statuses')
    op.drop_table('elevator_statuses')
    op.drop_index(op.f('ix_accessible_entrances_updated_by'), table_name='accessible_entrances')
    op.drop_index(op.f('ix_accessible_entrances_id'), table_name='accessible_entrances')
    op.drop_index(op.f('ix_accessible_entrances_facility_id'), table_name='accessible_entrances')
    op.drop_index(op.f('ix_accessible_entrances_created_by'), table_name='accessible_entrances')
    op.drop_table('accessible_entrances')
    op.drop_index(op.f('ix_accessibility_waypoints_updated_by'), table_name='accessibility_waypoints')
    op.drop_index(op.f('ix_accessibility_waypoints_route_id'), table_name='accessibility_waypoints')
    op.drop_index(op.f('ix_accessibility_waypoints_id'), table_name='accessibility_waypoints')
    op.drop_index(op.f('ix_accessibility_waypoints_created_by'), table_name='accessibility_waypoints')
    op.drop_table('accessibility_waypoints')
    op.drop_index(op.f('ix_accessibility_barriers_zone_id'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_venue_id'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_updated_by'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_status'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_severity'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_id'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_created_by'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_barrier_type'), table_name='accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_barriers_associated_facility_id'), table_name='accessibility_barriers')
    op.drop_table('accessibility_barriers')
    op.drop_index(op.f('ix_accessibility_routes_venue_id'), table_name='accessibility_routes')
    op.drop_index(op.f('ix_accessibility_routes_updated_by'), table_name='accessibility_routes')
    op.drop_index(op.f('ix_accessibility_routes_status'), table_name='accessibility_routes')
    op.drop_index(op.f('ix_accessibility_routes_id'), table_name='accessibility_routes')
    op.drop_index(op.f('ix_accessibility_routes_created_by'), table_name='accessibility_routes')
    op.drop_table('accessibility_routes')
    op.drop_index(op.f('ix_accessibility_maps_venue_id'), table_name='accessibility_maps')
    op.drop_index(op.f('ix_accessibility_maps_updated_by'), table_name='accessibility_maps')
    op.drop_index(op.f('ix_accessibility_maps_status'), table_name='accessibility_maps')
    op.drop_index(op.f('ix_accessibility_maps_id'), table_name='accessibility_maps')
    op.drop_index(op.f('ix_accessibility_maps_created_by'), table_name='accessibility_maps')
    op.drop_table('accessibility_maps')
    op.drop_index(op.f('ix_accessibility_facilities_venue_id'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_updated_by'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_status'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_name'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_id'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_facility_type'), table_name='accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_facilities_created_by'), table_name='accessibility_facilities')
    op.drop_table('accessibility_facilities')
    op.drop_index(op.f('ix_accessibility_audits_venue_id'), table_name='accessibility_audits')
    op.drop_index(op.f('ix_accessibility_audits_updated_by'), table_name='accessibility_audits')
    op.drop_index(op.f('ix_accessibility_audits_id'), table_name='accessibility_audits')
    op.drop_index(op.f('ix_accessibility_audits_created_by'), table_name='accessibility_audits')
    op.drop_table('accessibility_audits')
    # ### end Alembic commands ###
